# Generated by Django 2.2.7 on 2019-11-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_auto_20191119_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='call_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
