# Generated by Django 2.2.7 on 2019-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20191119_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='call_date',
            field=models.DateField(default=None),
        ),
    ]
