# Generated by Django 2.2.7 on 2019-12-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_auto_20191119_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='call_date',
            field=models.DateField(default=None, help_text='MM/DD/YYYY'),
        ),
    ]
