# Generated by Django 2.2.7 on 2019-11-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_country_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
    ]
