# Generated by Django 2.2.7 on 2019-12-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_auto_20191203_1324'),
        ('call', '0005_auto_20191202_1041'),
    ]

    operations = [
    ]
